language: node_js
node_js:
  - 6
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g codeclimate-test-reporter
cache:
  directories:
    - node_modules
    - yarn
script:
  - yarn run build
  - yarn run coverage
  - codeclimate-test-reporter < coverage/lcov.info